baseURL = "https://renzenicolai.nl/"
languageCode = "en-us"
title = "Renze's website"
theme = "minimal"
googleAnalytics = ""

[params]
    author = "Renze Nicolai"
    description = "My personal blog"
    githubUsername = "renzenicolai"
    accent = "#f04300"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    profilePic = "/avatar.jpg"
    copyright = "&copy; Renze Nicolai 2021"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 2

[[menu.main]]
    url = "/company"
    name = "Company"
    weight = 3

#[[menu.main]]
#    url = "/about/"
#    name = "About me"
#    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:info@renzenicolai.nl"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/renzenicolai/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/renzenicolai/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/renze-nicolai-75b243a5/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://t.me/r3nz3"
    name = "telegram"
    weight = 5

[markup.goldmark.renderer]
unsafe= true
