baseurl = "https://example.com/"
title = "Renze Nicolai"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[taxonomies]
  series = "series"

[params]
    author = "Renze Nicolai"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Hacker, IoT enthousiast, Electrical Engineer and Software Developer
    """
    publicationYear = "2019"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

[outputs]
    section = ["JSON", "HTML"]

#[[menu.main]]
#    identifier = "blog"
#    name = "Blog" #If display text link, cancel comment out
#    pre = "<i class='fa fa-book-open fa-lg'></i>" #Choose your favorite font from Font Awesome
#    url = "/blog/"
#    weight = 10

[[menu.main]]
    identifier = "twitter"
    name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/renzenicolai"
    weight = 20

[[menu.main]]
    identifier = "github"
    name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/renzenicolai"
    weight = 30

[[menu.main]]
    identifier = "email"
    name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:renze@rnplus.nl"
    weight = 40

[[menu.main]]
    identifier = "telegram"
    name = "Telegram"
    pre = "<i class='fab fa-telegram fa-lg'></i>"
    url = "https://t.me/r3nz3"
    weight = 50
